### ISSUE TITLE
Can only install version 1.0.2 from Obsidian and not 1.1.0

### ISSUE THREAD

**Issue by Toxe** [alvaro-cas/kindle-csv-converter-obsidian#2]
I tried installing the plugin from Obsidian but I only see version 1.0.2 and not the newer version 1.1.0. Replacing the 1.0.2 files to use the newer version works fine though.

**Comment by alvaro-cas** [comment]
Hello, yep. The documents called ["versions.json"](https://github.com/alvaro-cas/kindle-csv-converter-obsidian/blob/main/versions.json) and ["manifest.json"](https://github.com/alvaro-cas/kindle-csv-converter-obsidian/blob/main/manifest.json) were not updated, but now they have been fixed.
