### ISSUE TITLE
Importing German CSV file creates only Highlights but no Notes

### ISSUE THREAD

**Issue by Toxe** [alvaro-cas/kindle-csv-converter-obsidian#3]
When I import the attached CSV file I only get highlights but no notes. Each note will be imported as a highlight.

The file has been exported from a Kindle set to German.

[Das Zettelkasten-Prinzip_ Erfolgreich wissenschaftlich Schreiben und Studi...tebook.csv](https://github.com/alvaro-cas/kindle-csv-converter-obsidian/files/14342476/Das.Zettelkasten-Prinzip_.Erfolgreich.wissenschaftlich.Schreiben.und.Studi.tebook.csv)

**Comment by alvaro-cas** [comment]
Hello, it is now fixed in version [1.2.0](https://github.com/alvaro-cas/kindle-csv-converter-obsidian/releases/tag/1.2.0)
