### ISSUE TITLE
Importing German My Clippings.txt only creates the file but doesn't import anything

### ISSUE THREAD

**Issue by Toxe** [alvaro-cas/kindle-csv-converter-obsidian#4]
When importing the attached file I get a note that is basically empty. Probably another issue with a file generated on a German Kindle.

```
==Your Kindle Notes For:== Das Zettelkasten-Prinzip: Erfolgreich wissenschaftlich Schreiben und Studieren mit effektiven Notizen __by Ahrens, Sönke__


```

[My Clippings.txt](https://github.com/alvaro-cas/kindle-csv-converter-obsidian/files/14342619/My.Clippings.txt)

**Comment by alvaro-cas** [comment]
Hello, it is now fixed in version [1.2.0](https://github.com/alvaro-cas/kindle-csv-converter-obsidian/releases/tag/1.2.0)
