### ISSUE TITLE
Cannot import clippings from manually imported books

### ISSUE THREAD

**Issue by molnar-atesz** [alvaro-cas/kindle-csv-converter-obsidian#5]
Hey! First of all, I love your plugin and really appreaciate you've created it.

So the issue I faced with is when I wanna import clippings from a book which was not saved in an official kindle store book, e.g. from a book bundle, or simply I uploaded a manually transformed book (from pdf to epub), the plugin not able to process it. It throws an error:
```js
Uncaught TypeError: Cannot read properties of undefined (reading 'split')
    at Clippings.createFileClippings (plugin:kindle-csv-converter:186:39)
    at eval (plugin:kindle-csv-converter:143:14)
    at HTMLButtonElement.<anonymous> (app.js:1:1464673)
```

The problem is, that in such case, many times there is no page information and the clipping is saved in the following format:
```md
Perfect Software And Other Illusions About Testing (Weinberg, Gerald)
- Your Highlight at location 219-219 | Added on Saturday, 5 March 2022 11:48:35

Testing gathers information about a product; it does not fix things it finds that are wrong.
```

on the contrary when the page info is available then it saves like this:
```md
Code That Fits in Your Head (Attila Molnár's Library) (Mark Seemann)
- Your Highlight on page 347 | location 5073-5074 | Added on Thursday, 5 May 2022 06:37:20

A deterministic method without side effects is referentially transparent. It’s also known as a pure function.
```

It can be resolved to modify [the part where you extract the location info](https://github.com/alvaro-cas/kindle-csv-converter-obsidian/blob/7216605ac4106e87a33e7076554369ce2d4cafca/src/modal_clippings.ts#L126)

**Comment by molnar-atesz** [comment]
I browsed your code a bit more and found another potential place where the location extraction might go wrong. The place where you define the location [in modal_read.ts](https://github.com/alvaro-cas/kindle-csv-converter-obsidian/blob/7216605ac4106e87a33e7076554369ce2d4cafca/src/modal_read.ts#L101) you assume it will contain a page info, something like: "Your Highlight **on** page 347" however it in the following format "Your Highlight **at** location 219-219".
Would be better to match against `location \d{1,}-\d{1,}`

**Comment by alvaro-cas** [comment]
Hello, I was able to solve the problem by making some changes to [these lines](https://github.com/alvaro-cas/kindle-csv-converter-obsidian/blob/d49a01f4121238b529860c82c862f94b9875d6d5/src/modal_read.ts#L106C1-L110C8). I will keep an eye on that because it might need language support in the future.
